### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by thaarbach** [patrickfav/id-mask#3]
Hi

I just want to know, if this project is maintained. We are currently using HashId, but we would like to switch to IdMask.

**Comment by patrickfav** [comment]
Hi,

Not actively to be honest. I do think it works fine, however I do not use it for production currently.

**Comment by Radiergummi** [comment]
Any particular reason why you don't use it for production, or do you just not have a particular use case for it? I've hit a problem which would require an ID schema just like id-mask, but I'm wondering whether you've hit any limitations not mentioned in the original blog post?
